language: python
python:
- '2.7'
- '3.5'

env:
  - EXTRAS='[test]'
  - EXTRAS='[test,queuable,sentry,krb]'
  global:
        # see https://github.com/travis-ci/travis-ci/issues/7940
        - BOTO_CONFIG=/dev/null

install:
  - pip install -e .${EXTRAS}
before_script:
  - flake8 .
script:
- py.test
deploy:
  provider: pypi
  user: planet
  password:
    secure: EgEXpqXu2Iyi7nFuZrFmWBavvOil5r8ctqHGQ6BT2J5+qqE/K1OXblt/l0IcVYryoFTOAyB36Dti4+zgeGmcA+UrvKZyyIT8z0zWyIS/iLWhjiXDJdrDU0zVWXRVC5/AsgsxUkJMVVCke/dxUpIbLNuVV2jwUd3k0VGw+q2XR7Q=
  distributions: "sdist bdist_wheel"
  skip_existing: true
  on:
    branch: master
    tags: true
    repo: planetlabs/datalake
