language: python
python:
- '2.7'
install:
- pip install -e .[test]
before_script:
  - flake8 .
script:
- py.test
deploy:
  provider: pypi
  user: planet
  password:
    secure: EgEXpqXu2Iyi7nFuZrFmWBavvOil5r8ctqHGQ6BT2J5+qqE/K1OXblt/l0IcVYryoFTOAyB36Dti4+zgeGmcA+UrvKZyyIT8z0zWyIS/iLWhjiXDJdrDU0zVWXRVC5/AsgsxUkJMVVCke/dxUpIbLNuVV2jwUd3k0VGw+q2XR7Q=
  on:
    tags: true
    repo: planetlabs/datalake
