services: docker
dist: focal

env:
  global:
    - DOCKER_USERNAME: planetdatalake
    - secure: cF1f4bTOi52fyPcsJnaOOr33ghNZUQPnHEOwtXaRX0fZ1X6mRW9XrFOaMScZOhWEIlV7RteuEIoxIaJVN8ZWKHVZIh7/815quUmcOMhTRboHHMnGQPaXDYEmmhbPEg1uxjKTrGBRD5L/KZ2XUFqkobgb17Ju1QAH+K91hJJ6qes=
    # Pypi tokens are too long for a single value, so this uses two variables named PYPI_TOKEN1 and PYPI_TOKEN2
    - secure: "IjQo1V9ebdL9SNRtkt/3e83CIr8e/J8IfscGro8S+2ntrWY4/uaukL75sTq9YcfGW/2Rimp/nluHet/l/JXHWMM7hOsWjuqlnO8Rf559NlxRCHrb0GX9TLnwm7wcz1Zv838YPFHAXzljXrnoC5MeZ9/nhrB2ui0tzGpq5LzEY+Y="
    - secure: "UStKQvWEgPybT0pj1B2VE63ClN2CZ1n4d349RdehNfuaU0ng8s3l2GF76zQY9NbW+8x7NjZwmzkfoXhc+eMQhWu54z0GN7nF2AVvQGCpU6nztOu9gHWVCkHjL+v8tDnV5qRrK69nuZwLyGQ6RfjnlmzarAYQjIIAdvukEHHY16U="

_python_template: &_python_template
  language: python
  stage: test
  before_install: cd client/
  install: pip install -e .[test]
  script: py.test
  before_deploy: sudo cp /usr/bin/wget /usr/bin/_wget && echo -e '#!/bin/bash\n/usr/bin/_wget -nv -O - https://bootstrap.pypa.io/2.7/get-pip.py' | sudo tee /usr/bin/wget
  after_deploy: sudo mv /usr/bin/_wget /usr/bin/wget
  deploy:
    provider: pypi
    edge: true
    username: "__token__"
    password: $PYPI_TOKEN1$PYPI_TOKEN2
    distributions: "sdist bdist_wheel"
    skip_existing: true
    skip_cleanup: true
    on:
      branch: master
      tags: true
      repo: planetlabs/datalake

jobs:
  include:
  - <<: *_python_template
    name: py27 bare
    python: 2.7
    before_script: flake8 .
  - <<: *_python_template
    name: py35 bare
    python: 3.5
  - <<: *_python_template
    name: py27 with extras
    python: 2.7
    install: pip install -e .[test,queuable,sentry]
  - <<: *_python_template
    name: py35 with extras
    python: 3.5
    install: pip install -e .[test,queuable,sentry]
  - dist: bionic
    name: docker
    stage: test
    script:
      - make test
    deploy:
      provider: script
      script:
        - make push
      on:
        branch: master
        repo: planetlabs/datalake
